/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TurnOffGroupReplySchema {
  lightingGroup: {
    location: string;
    state: "ON" | "OFF";
    /**
     * Devices is device ids
     */
    devices: string[];
    createdAt: string;
    updatedAt: string;
  };
  lightingDevices: {
    id: string;
    name: string;
    brand: string;
    power: string;
    lumens: string;
    lightTemperatureKelvin: number;
    resourceMs: number;
    price: string;
    currency: string;
    sellersWebsite: string;
    images: string[];
    placeOfInstallation: string;
    state: "ON" | "OFF" | "IN_STOCK" | "DECOMMISSIONED";
    history: {
      placeOfInstallation: string;
      turnedOnAt: string | null;
      turnedOffAt: string | null;
      workedMs: number | null;
    }[];
    createdAt: string;
    updatedAt: string;
  }[];
}
