/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UpdateLightingDevicesReplySchema = {
  id: string;
  name: string;
  brand: string;
  power: string;
  lumens: string;
  lightTemperatureKelvin: number;
  resourceMs: number;
  price: string;
  currency: string;
  sellersWebsite: string;
  images: string[];
  placeOfInstallation: string;
  state: "ON" | "OFF" | "IN_STOCK" | "DECOMMISSIONED";
  history: {
    placeOfInstallation: string;
    turnedOnAt: string;
    turnedOffAt: string;
    workedMs: number;
  }[];
  createdAt: string;
  updatedAt: string;
}[];
