version: '3.7'

services:
  mongodb:
    image: mongo
    ports:
      - '127.0.0.1:27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wirenboard
      - MONGO_INITDB_ROOT_PASSWORD=def37057-1c5f-4e73-bf89-37241ed42453
    volumes:
      - ./mongodb:/data
