version: "3.7"
services:
  rethinkdb:
    restart: "always"
    image: rethinkdb:2.4.2
    ports:
      - "127.0.0.1:29015:29015"
      - "127.0.0.1:28015:28015"
      - "127.0.0.1:27015:8080"
    volumes:
      - rethinkdb_data:/data
  rethinkdb_test:
    restart: "always"
    image: rethinkdb:2.4.2
    ports:
      - "127.0.0.1:29016:29015"
      - "127.0.0.1:28016:28015"
      - "127.0.0.1:27016:8080"
    volumes:
      - rethinkdb_data_test:/data
