export enum EventBus {
  WB_APPEARED = 'WB_APPEARED',

  WB_PUBLISH_MESSAGE = 'WB_PUBLISH_MESSAGE',

  HD_APPEARED = 'HD_APPEARED',

  GQL_PUBLISH_SUBSCRIPTION_EVENT = 'GQL_PUBLISH_SUBSCRIPTION_EVENT',

  ZIGBEE_2_MQTT_PUBLISH_MESSAGE = 'ZIGBEE_2_MQTT_PUBLISH_MESSAGE',
}
