export enum EventBus {
  HARDWARE_DEVICE_APPEARED = 'HARDWARE_DEVICE_APPEARED',

  WB_PUBLISH_MESSAGE = 'WB_PUBLISH_MESSAGE',

  HYPERION_DEVICE_APPEARED = 'HYPERION_DEVICE_APPEARED',

  GQL_PUBLISH_SUBSCRIPTION_EVENT = 'GQL_PUBLISH_SUBSCRIPTION_EVENT',

  ZIGBEE_2_MQTT_SEND_MESSAGE = 'ZIGBEE_2_MQTT_SEND_MESSAGE',
}
