-- AlterTable
ALTER TABLE "Control" ADD COLUMN     "enum" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "off" TEXT NOT NULL DEFAULT '0',
ADD COLUMN     "on" TEXT NOT NULL DEFAULT '1',
ADD COLUMN     "presets" TEXT NOT NULL DEFAULT '{}',
ADD COLUMN     "step" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "toggle" TEXT NOT NULL DEFAULT 'UNSPECIFIED';

-- AlterTable
ALTER TABLE "Device" ADD COLUMN     "order" INTEGER NOT NULL DEFAULT 0;
