export enum Errors {
  UNEXPECTED_BEHAVIOR = "UNEXPECTED_BEHAVIOR",
  INVALID_ARGUMENTS = "INVALID_ARGUMENTS",
  INSERT_FAILED = "INSERT_FAILED",
  UPDATE_FAILED = "UPDATE_FAILED",
  MOVE_FAILED = "MOVE_FAILED",
}
