export enum LightingGroupLocation {
  LIVING_ROOM_CEILING_GROUP_1 = "LIVING_ROOM_CEILING_GROUP_1",
  LIVING_ROOM_CEILING_GROUP_2 = "LIVING_ROOM_CEILING_GROUP_2",
  LIVING_ROOM_CEILING_GROUP_3 = "LIVING_ROOM_CEILING_GROUP_3",
  LIVING_ROOM_CEILING_GROUP_4 = "LIVING_ROOM_CEILING_GROUP_4",
  LIVING_ROOM_CEILING_GROUP_5 = "LIVING_ROOM_CEILING_GROUP_5",
  LIVING_ROOM_CEILING_GROUP_6 = "LIVING_ROOM_CEILING_GROUP_6",
  LIVING_ROOM_CEILING_GROUP_7 = "LIVING_ROOM_CEILING_GROUP_7",
  LIVING_ROOM_KITCHEN_GROUP = "LIVING_ROOM_KITCHEN_GROUP",
  LIVING_ROOM_STAND_GROUP = "LIVING_ROOM_STAND_GROUP",
  GAMING_ROOM_CEILING_GROUP_1 = "GAMING_ROOM_CEILING_GROUP_1",
  GAMING_ROOM_CEILING_GROUP_2 = "GAMING_ROOM_CEILING_GROUP_2",
  GAMING_ROOM_CHANDELIER_GROUP = "GAMING_ROOM_CHANDELIER_GROUP",
  GAMING_ROOM_BEDSIDE_TABLE_GROUP = "GAMING_ROOM_BEDSIDE_TABLE_GROUP",
  GAMING_ROOM_TV_STAND_GROUP = "GAMING_ROOM_TV_STAND_GROUP",
  GAMING_ROOM_WORKBENCH_GROUP = "GAMING_ROOM_WORKBENCH_GROUP",
  BATH_ROOM_GROUP = "BATH_ROOM_GROUP",
  BATH_ROOM_MIRROR_GROUP = "BATH_ROOM_MIRROR_GROUP",
  BED_ROOM_CHANDELIER_GROUP = "BED_ROOM_CHANDELIER_GROUP",
  BED_ROOM_BEDSIDE_TABLE_GROUP = "BED_ROOM_BEDSIDE_TABLE_GROUP",
  BED_ROOM_STAND_GROUP = "BED_ROOM_STAND_GROUP",
  HALL_GROUP_1 = "HALL_GROUP_1",
  HALL_GROUP_2 = "HALL_GROUP_2",
  HALLWAY_GROUP = "HALLWAY_GROUP",
  PORCH_GROUP = "PORCH_GROUP",
  UTILITY_ROOM_CEILING_GROUP = "UTILITY_ROOM_CEILING_GROUP",
  UTILITY_ROOM_MIRROR_GROUP = "UTILITY_ROOM_MIRROR_GROUP",
  CABINET_CEILING_GROUP_1 = "CABINET_CEILING_GROUP_1",
  CABINET_CEILING_GROUP_2 = "CABINET_CEILING_GROUP_2",
  CABINET_WORKBENCH_GROUP_1 = "CABINET_WORKBENCH_GROUP_1",
  CABINET_WORKBENCH_GROUP_2 = "CABINET_WORKBENCH_GROUP_2",
  ENGINEERING_GROUP = "ENGINEERING_GROUP",
  ROOF_GROUP = "ROOF_GROUP",
  LED_GROUP = "LED_GROUP",
  INFRARED_SEARCHLIGHT_GROUP = "INFRARED_SEARCHLIGHT_GROUP",
  FACADE_GROUP_1 = "FACADE_GROUP_1",
  FACADE_GROUP_2 = "FACADE_GROUP_2",
  FACADE_GROUP_3 = "FACADE_GROUP_3",
  FACADE_GROUP_4 = "FACADE_GROUP_4",
  FACADE_GROUP_5 = "FACADE_GROUP_5",
}

export enum LightingGroupState {
  ON = "ON",
  OFF = "OFF",
}

export type LightingGroup = {
  readonly location: string;
  readonly state: LightingGroupState;
  readonly devices: string[];
  readonly createdAt: string;
  readonly updatedAt: string;
};
