#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

cd ./mett

echo "🚀 Build Mett..."

yarn build

cd ../rayner

echo "🚀 Build Rayner..."

yarn build:check

cd ../swan

echo "🚀 Build Swan..."

yarn build:check
