#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

cd ./packages/rayner

echo "🚀 Build rayner..."

yarn build:check

echo "✅ Rayner was built successsful"

cd ../swan

echo "🚀 Build swan..."

yarn build:check

echo "✅ Swan was built successsful"
